name: webserver

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file:
      - config.env
      - path: .local.env
        required: false
    ports:
      - 3000:3000
    volumes:
      - ./configs:/app/config
      - ${HOME}/homepage/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - multimedia
      - tools
      - webserver

networks:
  multimedia:
    name: multimedia
    external: true
  tools:
    name: tools
    external: true
  webserver:
    name: webserver
    external: true
