name: webserver

services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped
    networks:
      - webserver

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file:
      - ../docker.env
      - config.env
      - path: .local.env
        required: false
    ports:
      - 3000
    volumes:
      - ./configs:/app/config
      - /home/haitv/homepage/images:/app/public/images
    restart: unless-stopped
    networks:
      - multimedia
      - tools
      - webserver

networks:
  multimedia:
    name: multimedia
    external: true
  tools:
    name: tools
    external: true
  webserver:
    name: webserver
    external: true
