title: ENC[AES256_GCM,data:69rL1aHDJ/8ZLNsRGq97US4=,iv:J0mAu7X88ta4+NPW3g+K/W9fJjXHNHKBl2TGYxLDffw=,tag:q+AttqXscv2RDJtyaPBooQ==,type:str]
providers:
    weatherapi: ENC[AES256_GCM,data:+obr9Wy42/UAQh5vp+NILsFKcCYXxnSo+LSzBnmT0K8=,iv:BVGkUP0AElSYWCYMTplYAgm7Adh4fQDCXGeP0rgm4hs=,tag:FNyMYm3gwXKPIYGA+c/kLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-18T20:30:53Z"
    mac: ENC[AES256_GCM,data:oXLm0zrJGa9D4gRxA5mGwKnu+wbvB089wwJwFeXt4zAysYL+TUbNW8qivz0CC0+ZF3XtKnEYVkmYiOOB9smImYAQSf6dhyHzSUR0X1CFCSbr6hkGlZXVcdy9Vl82JRUl4TK07gWdNGwwbYhtYqwXfie1uHsk1P6KbSRP90ipte8=,iv:7pWtPVYsDaeMIIwSZp0o4vsdhirL34RPKg8NkF4ZTDE=,tag:0zAnd6tw9TWuzr/JjctuUg==,type:str]
    pgp:
        - created_at: "2024-04-18T20:20:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1eHMvPjG5BMARAAsL63tvj/PwJCKaL+VgldFtFrEPUI5hboxRCFPSfZp7sy
            EvlisGt60mNAP8PiiDeuKB5Osy8IbUK4MtHCnJoeOzGaK+SRsX86Vyg6WiGxEu/M
            A1K8S+ebATyi6w6CFZt2D+l9hEoEXAxSy6fCNUcU6yToG8a7U5V0IdAfcopgRnpn
            j04CjnFn/9rR+L9A1tt1gnR7OEot9cPzqkvuDPrZx1wYVYNmY8s9hHFRXqx+3hKs
            B1nbBLtBqfFm6ytmdX605qGIBqxjkC4j9egvtRAJMk9Epin50Vng+AxknmLlE4DM
            YlQ888xHDgNdnwIHIZrsSYtzg2pL3MEQeEDbYsQz7SNhTfiNMN+Far4gs6Wq2lTf
            9L7o3mcw13xCoa/PP0np3zi41lL2/vSoS2aQEiymLbiL/1mf60/q4w4Y5P8wlq2v
            7KBOQ7MSllVmu9VHl9Rya69NgzPNcdd1tJ9FMbrTBpcPsLrBqpR/uTaEjWYWEkR6
            GjBAE6fObTnw34iytYXaA7iUto4x5ZRUhFGAQP2e18Biu5HrB2SobPdU+UZrjDFj
            7wryjjQ232VYFOIwqa/mxKoEF49QFNOf9rt2ctoCQg+adugCWdVSjLD8001uzeiA
            /MFIq8QZKxzSEW/eUH73wdaJV3i/390fJAeIIZbEmGaXZ09EC1TtCAfQts14NZ/S
            XAG4EpUWuosG6FvQZjbUKwqVilmjgrOmHUA7hTGLAlcltzZhC2futZHpw36ynxe7
            XqiQFDnA2lJP3yMwwR3/bXWby2Dq8lrgIFAg+nnmquj8SbWojxqhck6XEFjO
            =rTD/
            -----END PGP MESSAGE-----
          fp: 8E96E1CC979A93834A5F37AB8D8549888B14F99E
    unencrypted_suffix: _unencrypted
    version: 3.8.1
