title: HaiViTa Dashboard

background:
    image: /images/background.jpg
    # blur: sm          # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
    # saturate: 50      # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
    # brightness: 50    # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness    
    opacity: 30         # 0-100

favicon: /images/favicon.ico

theme: dark
color: zinc

quicklaunch:
  searchDescriptions: true
  showSearchSuggestions: true
  provider: google

layout:
  System:
    style: row
    columns: 3
  Media:
    style: row
    columns: 3
  Calendar:
    header: false
  Data1:
    header: false
  Data2:
    header: false
  Services:
    style: row
    columns: 4
  Cloud:
    style: row
    columns: 4

useEqualHeights: true
hideVersion: true

providers:
    weatherapi: {{HOMEPAGE_VAR_WEATHERAPI}}
