---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- logo:
    icon: /images/logo.png

- greeting:
      text_size: xl
      text: HaiViTa

# - resources:
#       label: System
#       cpu: true
#       memory: true

# - resources:
#       label: Storage
#       disk:
#        - /
#        - /mnt/data

- search:
      provider: google
      target: _blank

# 13:37
- datetime:
      text_size: xl
      format:
          timeStyle: short
          hourCycle: h23

- glances:
      url: https://glances.{{HOMEPAGE_VAR_DOMAIN}}
      username: {{HOMEPAGE_VAR_GLANCES_USER}} # optional if auth enabled in Glances
      password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}} # optional if auth enabled in Glances
      version: 4 # required only if running glances v4 or higher, defaults to 3
      cpu: true # optional, enabled by default, disable by setting to false
      mem: true # optional, enabled by default, disable by setting to false
      # cputemp: true # disabled by default
      # uptime: true # disabled by default
      # diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
      # expanded: true # show the expanded view
      label: System # optional

- glances:
      url: https://glances.{{HOMEPAGE_VAR_DOMAIN}}
      username: {{HOMEPAGE_VAR_GLANCES_USER}} # optional if auth enabled in Glances
      password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}} # optional if auth enabled in Glances
      version: 4 # required only if running glances v4 or higher, defaults to 3
      cpu: false # optional, enabled by default, disable by setting to false
      mem: false # optional, enabled by default, disable by setting to false
      disk:
        - /Root
        - /Home
        - /Data
      #   - /media/Data
      diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
      # expanded: true # show the expanded view
      label: Disks # optional
